document.write( '<!DOCTYPE html>\n' );
document.write( '<html>\n' );
document.write( '\n' );
document.write( '    \n' );
document.write( '<head>\n' );
document.write( '<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n' );
document.write( '<style>\n' );
document.write( 'body {\n' );
document.write( '  margin: 0;\n' );
document.write( '  font-family: Arial, Helvetica, sans-serif;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.top-container {\n' );
document.write( '  background-color: #f1f1f1;\n' );
document.write( '  padding: 30px;\n' );
document.write( '  text-align: center;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.header {\n' );
document.write( '  padding: 10px 16px;\n' );
document.write( '  background: black;\n' );
document.write( '  color: #f1f1f1;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.content {\n' );
document.write( '  padding: 16px;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.sticky {\n' );
document.write( '  position: fixed;\n' );
document.write( '  top: 0;\n' );
document.write( '  width: 100%;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.sticky + .content {\n' );
document.write( '  padding-top: 102px;\n' );
document.write( '}\n' );
document.write( '</style>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '\n' );
document.write( '<div class=\"header\" id=\"myHeader\">\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n' );
document.write( '<style>\n' );
document.write( 'body {\n' );
document.write( '  font-family: \"Lato\", sans-serif;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.sidenav {\n' );
document.write( '  height: 100%;\n' );
document.write( '  width: 0;\n' );
document.write( '  position: fixed;\n' );
document.write( '  z-index: 1;\n' );
document.write( '  top: 0;\n' );
document.write( '  left: 0;\n' );
document.write( '  background-color: #111;\n' );
document.write( '  overflow-x: hidden;\n' );
document.write( '  transition: 0.5s;\n' );
document.write( '  padding-top: 60px;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.sidenav a {\n' );
document.write( '  padding: 8px 8px 8px 32px;\n' );
document.write( '  text-decoration: none;\n' );
document.write( '  font-size: 25px;\n' );
document.write( '  color: #818181;\n' );
document.write( '  display: block;\n' );
document.write( '  transition: 0.3s;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.sidenav a:hover {\n' );
document.write( '  color: #f1f1f1;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.sidenav .closebtn {\n' );
document.write( '  position: absolute;\n' );
document.write( '  top: 0;\n' );
document.write( '  right: 25px;\n' );
document.write( '  font-size: 36px;\n' );
document.write( '  margin-left: 50px;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media screen and (max-height: 450px) {\n' );
document.write( '  .sidenav {padding-top: 15px;}\n' );
document.write( '  .sidenav a {font-size: 18px;}\n' );
document.write( '}\n' );
document.write( '</style>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '\n' );
document.write( '<div id=\"mySidenav\" class=\"sidenav\">\n' );
document.write( '   <center> <img src=\"https://1.bp.blogspot.com/-__QMfyzgCnM/YPFP382v49I/AAAAAAAAIFA/E6pN36VUczIumlrvjVn6smVBEe-0Oa2WwCNcBGAsYHQ/s1080/IMG_20210615_190240.jpg\" width=\"150\"height=\"80\"></center>\n' );
document.write( '  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\n' );
document.write( '  <a href=\"index.php">login</a>\n' );
document.write( '  <a href="https://google.com">Register</a>\n' );

document.write( '  <a href="mailto:professor@pharmatricks.in">Contact Us</a>\n' );
document.write( '  \n' );
document.write( '</div>\n' );
document.write( '<span style=\"font-size:25px;cursor:pointer\" onclick=\"openNav()\"> &#9776;\n' );
document.write( '<font color="orange"><b>Pharmatricks.in</b></font>\n' );
document.write( '</span>\n' );
document.write( '<script>\n' );
document.write( 'function openNav() {\n' );
document.write( '  document.getElementById(\"mySidenav\").style.width = \"250px\";\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'function closeNav() {\n' );
document.write( '  document.getElementById(\"mySidenav\").style.width = \"0\";\n' );
document.write( '}\n' );
document.write( '</script>\n' );
document.write( '</div>\n' );
